### Learing NumPy

In [1]:
import numpy as np

### The Basics

In [ ]:
a = np.array([1, 2, 3], dtype='int16') # dtype = data type
print(f"a = {a}")

a = [1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(f"b = {b}")

b = [[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimention
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get Shape
print(a.shape)
print(b.shape) # (2, 3) 2 rows and 3 cols

(3,)
(2, 3)


In [13]:
# Get Type
print(a.dtype)
print(b.dtype)

int16
float64


In [15]:
# Get Size
print(a.itemsize) # bytes data
print(b.itemsize)

2
8


In [ ]:
# Total number of items
print(a.size) 
print(b.size)

3
6


In [ ]:
# Total Size
print(a.nbytes)
print(a.size * a.itemsize)

print(b.nbytes)
print(b.size * b.itemsize)

6
6
48
48


### Accessing/Changing specific elements, rows, columns, etc.

In [24]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [25]:
# Get Specific element [r, c]
a[1, 5]

np.int64(13)

In [26]:
# Get a Specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a Specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# [start_index : end_index : step_size]
a[0, 1:6:2]  # 1 to 5 index of 0-th row

array([2, 4, 6])

In [35]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [37]:
# Change a sequence of numbers
a[:, 2] = 5 # all elements of col-2 is set to 5
print(a)

a[:, 2] = [99, 99]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2 99  4  5  6  7]
 [ 8  9 99 11 12 20 14]]


#### 3D Example

In [40]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)
print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [50]:
# Get specific element (work outside in)
print(b[0,1,1]) # x=0(first 4) ,y=1(2nd row), z=1(2nd element)

print(b[:,1,:])

print(b[1,:,1])


4
[[3 4]
 [7 8]]
[6 8]


In [ ]:
# Replace
b[:,1,:] = [[9,9], [8,8]] # must give same dimension
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [60]:
# All 0s matrix
print("One Dimentional (5): ")
print(np.zeros(5))
print("Two Dimentional (2x3): ")
print(np.zeros((2, 3)))
print("Three Dimentional (2x3x2): ")
print(np.zeros((2, 3, 2)))
print("Four Dimentional (2x3x3x2): ")
print(np.zeros((2, 2, 2, 2)))

One Dimentional (5): 
[0. 0. 0. 0. 0.]
Two Dimentional (2x3): 
[[0. 0. 0.]
 [0. 0. 0.]]
Three Dimentional (2x3x2): 
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
Four Dimentional (2x3x3x2): 
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [61]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [64]:
# Any Other Number

# 2x2 matrix filled with 99 of type float32
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [68]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers
np.random.rand(4, 2) # 4x2 matrix filled with random numbers (0-1)

array([[0.91007205, 0.25401202],
       [0.78237878, 0.96083031],
       [0.08695878, 0.87632201],
       [0.60512593, 0.48272879]])

In [ ]:
# Random Integer values
np.random.randint(1, 7, size=(3,3)) # (1 to 6) values of 3x3 matrix

array([[1, 6, 4],
       [2, 6, 3],
       [4, 5, 6]], dtype=int32)

In [82]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Exercise
t = np.zeros((5,5), dtype='int32')
t[0, :] = t[4, :] = t[:, 0] = t[:, 4] = 1
t[2,2] = 9
print(t)

# Or,
t = np.ones((5,5), dtype='int32')
z = np.zeros((3,3), dtype='int32')
z[1,1] = 9
t[1:4, 1:4] = z

print(t)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful when coping arrays!

In [104]:
a = np.array([1,2,3])
b = a
b[0] = 100  # a also changes
print(a, b)

[100   2   3] [100   2   3]


In [103]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a, b)

[1 2 3] [100   2   3]


### Mathematics

In [105]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [106]:
a + 2

array([3, 4, 5, 6])

In [107]:
a - 2

array([-1,  0,  1,  2])

In [108]:
a * 2

array([2, 4, 6, 8])

In [109]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [110]:
b = np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [111]:
a + b

array([2, 2, 4, 4])

In [112]:
a ** 2

array([ 1,  4,  9, 16])

In [113]:
# Take sin value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [114]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear ALgebra

In [117]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
# Matrix Multiplication
np.matmul(a, b) # multiply 2 matrices (1st mats col must be equal to 2nd mat rows)

array([[6., 6.],
       [6., 6.]])

In [121]:
# Determinant of a Matrix
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
## Refencence docs (https://numpy.org/doc/stable/reference/routines.linalg.html)
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [123]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.min(stats)

np.int64(1)

In [125]:
np.max(stats)

np.int64(6)

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [127]:
np.max(stats, axis=1)

array([3, 6])

In [128]:
np.sum(stats)

np.int64(21)

### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
# reshape 2x4 to 4x2
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [136]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Load Data from File

In [147]:
filedata = np.genfromtxt('helpers/data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  21, 232, 242,  42, 334,   5,   5,   5,   6],
       [  1,   2,   3,   4,   4,   5,   5,   5,   2,   1],
       [  6,  31,  45,  66,  64,  99,   0,   7,  53, 474]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [148]:
filedata > 50

array([[False, False,  True,  True, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False,  True,
         True]])

In [149]:
filedata[filedata > 50]

array([232, 242, 334,  66,  64,  99,  53, 474], dtype=int32)

In [150]:
# We can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [152]:
# if any column has value > 50
np.any(filedata > 50, axis=0)

array([False, False,  True,  True,  True,  True, False, False,  True,
        True])

In [ ]:
# if all column has value >= 5
np.all(filedata >= 5, axis=0)

array([False, False, False, False, False,  True, False,  True, False,
       False])

In [158]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True,  True, False, False,  True,
        False]])

In [159]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False, False, False,  True,  True, False,
         True]])

In [ ]:
# Exercise
t = np.arange(1, 31).reshape(6, 5)
print(t)

# access 11,12, 16, 17
print(t[2:4, 0:2])

# access 2,,8,14,20
print(t[[0,1,2,3], [1,2,3,4]])

# access 4,5,24,25,29,30
print(t[[0,4,5], 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
